// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymixmyqbsuprgbtowrqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltaXhteXFic3VwcmdidG93cnF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzM3OTgsImV4cCI6MjA2Mzg0OTc5OH0.S8-JhgeH7fY4JzdPbYr19VwlpL7HsyomJmfqpk0M78c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);